#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# The hook should exit with non-zero status after issuing an appropriate message if it wants to prevent the commit.
#
# In the project directory, run `git config core.hooksPath hooks/` to install the hooks of this 
# directory (without affecting how git hooks work for other projects).
# https://www.atlassian.com/git/tutorials/git-hooks#local-hooks
# https://near-foundation.atlassian.net/browse/ENG-149

diff=$(cargo fmt -- --check)
result=$?

RED='\033[0;31m'
RESET='\033[0m' # No Color

if [[ ${result} -ne 0 ]] ; then
    printf "${RED}Please run \`cargo fmt\` before committing code. Here is the current result of \`cargo fmt -- --check\`:\n${RESET}"
    echo $diff
    exit 1
fi

exit 0
