[package]
autobins = false
edition.workspace = true
name = "workspaces-tests"
publish = false
version = "0.1.0"

[dependencies]
cargo-near-build = "0.11.0"
near-api = "0.8"
near-crypto = "0.34"
near-sandbox = "0.3"
pretty_assertions = "1"
tokio = { version = "1", features = ["full"] }
testresult = "0.4.1"

near-sdk = { workspace = true, default-features = false, features = [
    "unstable",
    "unit-testing",
    "legacy",
    "non-contract-usage"
] }
near-sdk-contract-tools = { workspace = true, features = ["unstable"] }

[features]
unstable = ["near-sdk/unstable"]
