[tasks.build]
clear = true
script = """
rustup target add wasm32-unknown-unknown
cargo build --package workspaces-tests --target wasm32-unknown-unknown --release
"""

[tasks.test]
clear = true
dependencies = ["build"]
script = """
#!/usr/bin/env bash
set -e

if [[ -n $1 ]]; then
    cargo test --package workspaces-tests --test "$1" "$2" -- --nocapture
else
    # don't show all output if running all tests
    cargo test --package workspaces-tests
fi
"""

[tasks.nextest]
clear = true
dependencies = ["build"]
script = """
#!/usr/bin/env bash
set -e

if [[ -n $2 ]]; then
    cargo nextest run --package workspaces-tests --no-default-features --features near-sdk-5 --test "$1" -E "test($2)"
    cargo nextest run --package workspaces-tests --no-default-features --features near-sdk-4 --test "$1" -E "test($2)"
elif [[ -n $1 ]]; then
    cargo nextest run --package workspaces-tests --no-default-features --features near-sdk-5 --test "$1"
    cargo nextest run --package workspaces-tests --no-default-features --features near-sdk-4 --test "$1"
else
    cargo nextest run --package workspaces-tests --no-default-features --features near-sdk-5
    cargo nextest run --package workspaces-tests --no-default-features --features near-sdk-4
fi
"""
