name: Rust

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

env:
  CARGO_TERM_COLOR: always

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.86
          components: rustfmt
      - name: Check formatting
        run: >
          echo "::echo::on";
          cargo fmt -- --check;
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.86
          components: clippy
          targets: wasm32-unknown-unknown
      - name: Run linter
        run: cargo clippy --target wasm32-unknown-unknown -- -D warnings
  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.86
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@v2
      - name: Run unit and integration tests
        run: cargo nextest run --workspace --exclude workspaces-tests
      - name: Run doctests
        run: cargo test --doc
  workspaces-test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libudev-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.86
          targets: wasm32-unknown-unknown
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-make,nextest,cargo-near@0.17.0
      - uses: Swatinem/rust-cache@v2
      - name: Run workspaces tests
        run: cd workspaces-tests && cargo make nextest
